### PR TITLE
Accordion doesn't work in ST2 PR or newer

### PR DESCRIPTION
**Pull request by Odi55555**
collapse/Expand and displaying the title of the titlebar don't work in ST2 PR or newer

changed: 
title in insertTitle()
and getEl() in collapse()

### CODE REVIEW

**Comment by Arise** [comment]
Just tested. Seems to display title now just fine and the collapsible action also works.

**Comment by Arise** [comment]
@Odi55555 the panels doesn't cover always the elements from subpages.

Don't know if this is ok, but I solved that problem with:

var elems = Ext.select("#"+component.id+" > div > div");
for (var i=1;i<elems.elements.length;i++){ //not the title
    elems.item(i).setVisible(false);
}   

inside collapse function.

Then did the same for expand function, but showing the items in elems array.

Also, a component.hide(); and a component.show(); in expand function were required to make scrolling lists work (they get stuck after hiding).

**Comment by jakerella** [comment]
I added the following CSS and things seem fixed. may be easier than what you have. Give it a try (and it's in my other pull request):

`.x-layout-accordion-item { overflow: hidden; }`

**Comment by mitchellsimoens** [comment]
There is a merge conflict here

**Comment by jakerella** [comment]
@Odi55555 can you see if the CSS styles I posted are sufficient to resolve your issue? It has already been merged, so maybe just try replacing your current copy with the latest?

**Comment by Odi55555** [comment]
@ jakerella
I don't think that a styles change could resolve this issue, because the title and the height were undefined. 

But I'm now on ST 2.1 and added other pull requests to resolve new issues. They were merged and thats maybe why here's a merge conflict. I'm closing this issue; This here is only interesting for somebody who tries to work with ST 2.0; for ST 2.1 everything should be fine now...

**Pull request closed without merging**
